
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")'
    


build:
  image: node:20
  tags:
    - ubuntu
  script:
    - npm install
    - npx prisma generate
    - npm run build



